openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Code Interpreter API"
paths:
  /code:
    post:
      code: "Start a new summarization task"
      operationId: "add"
      requestBody:
        description: "Code to execute on the server"
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                code:
                  type: "string"
      responses:
        "202":
          description: "Accepted. The task has been accepted for processing, but the processing has not been completed."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  task_id:
                    type: "string"
  /logs/{task_id}:
    get:
      result: "Get the logs of a code execution task"
      operationId: "get_logs"
      parameters:
      - name: "task_id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  summary:
                    type: "string"
        "202":
          description: "Accepted but not ready"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    type: "string"
    /files/{task_id}:
    get:
      summary: Get all files in a directory
      parameters:
        - in: path
          name: task_id
          required: true
          description: The ID of the task
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string
        '202':
          description: Processing
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
    servers:
      - url: http://localhost:8000
  /get_file/{task_id}/{file_name}:
    get:
      summary: Get a file by name
      parameters:
        - in: path
          name: task_id
          required: true
          description: The ID of the task
          schema:
            type: string
        - in: path
          name: file_name
          required: true
          description: The name of the file
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /logo.png:
    get:
      summary: "Get the plugin logo"
      operationId: "plugin_logo"
      responses:
        "200":
          description: "Successful operation"
          content:
            image/png: {}

  /.well-known/ai-plugin.json:
    get:
      summary: "Get the plugin manifest"
      operationId: "plugin_manifest"
      responses:
        "200":
          description: "Successful operation"
          content:
            text/json: {}

  /openapi.yaml:
    get:
      summary: "Get the OpenAPI specification"
      operationId: "openapi_spec"
      responses:
        "200":
          description: "Successful operation"
          content:
            text/yaml: {}
